# Generated by Django 5.1.4 on 2025-02-10 05:50

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('album', '0001_initial'),
        ('musician', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='albums',
            name='musician',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='musician.musician'),
        ),
        migrations.AlterField(
            model_name='albums',
            name='release_date',
            field=models.DateField(default=datetime.date(2025, 2, 10)),
        ),
    ]
