# Generated by Django 5.1.4 on 2025-02-07 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='practice_model',
            fields=[
                ('auto_field', models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
    ]
